title: My Personal Blog
description: "A place where I write about things I care about."
baseurl: ""  # 你可以设置为你的 GitHub Pages 子路径（如果有）
url: "https://australiaframe.github.io"
theme: "minima"  # 如果你选择了 Jekyll 默认主题，可以使用 minima
